# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'MovieList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoviesList
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Kingfisher', '~> 7.0'

  target 'MovieListTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher', '~> 7.0'

  end

  target 'MovieListUITests' do
    # Pods for testing
  end

end
